name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: 123456
          MYSQL_DATABASE: simpale_bank
          MYSQL_ROOT_PASSWORD: 1234567
        ports:
          - 3308
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: run migrations
        run: migrate -path db/migration -database “mysql://root:1234567@tcp(localhost:3308)/simple_bank” -verbose up
      - name: Test
        run: go test -v ./...
