name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest


    steps:
            
      - uses: mirromutth/mysql-action@v1.1
        with:
          
          container port: 3308 # Optional, default value is 3306. The port of container
          mysql database: 'simple_bank' # Optional, default value is "test". The specified database which will be create
          mysql root password: 1234567
          mysql user: root 
          mysql password: 1234567
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "migrate"
        run: $ curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
      - name: migrate 2
        run: $ echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
      - name: migrate 3
        run: $ apt-get update
      - name: migrate 4
        run: $ apt-get install -y migrate
               
      - name: run migrations
        run: migrate -path db/migration -database "mysql://root:1234567@tcp(localhost:3308)/simple_bank" -verbose up
      - name: Test
        run: go test -v ./...
